package main

import (
	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
	"github.com/gopherjs/vecty/prop"
)

// contactComponent
type contactComponent struct {
	vecty.Core
	disabled bool
	text     string
}

// Render renders the body
func (v *contactComponent) Render() vecty.ComponentOrHTML {
	return elem.Body(l(v.disabled),
		vecty.Markup(
			vecty.Style(
				"overflow",
				"hidden",
			),
		),
		elem.Header(
			vecty.Markup(
				vecty.Class(
					"container",
					"padding-16",
					"white",
					"bar",
					"top",
					"border-blue",
				),
				vecty.Style(
					"border-bottom",
					"1px",
				),
			),
			elem.Anchor(
				vecty.Markup(
					vecty.Class(
						"xlarge",
						"left",
					),
					vecty.MarkupIf(
						v.disabled,
						vecty.Class(
							"disabled",
						),
					),
					prop.Href("/"),
					vecty.Style(
						"text-decoration",
						"none",
					)),
				vecty.Text("« Home"),
			),
			elem.Anchor(
				vecty.Markup(
					prop.Href("/contact"),
				),
				elem.Image(
					vecty.Markup(
						vecty.Class(
							"xlarge",
							"right",
							"circle",
						),
						vecty.Style(
							"width",
							"32px",
						),
						vecty.Style(
							"height",
							"32px",
						),
						prop.Src("/app/avatar.jpg"),
					),
				),
			),
		),
		elem.Div(
			vecty.Markup(
				vecty.Class(
					"padding-32",
				),
			),
		),
		elem.Div(
			vecty.Markup(
				vecty.Class(
					"col", "l3", "m2",
					"padding",
				),
			),
		),
		elem.Div(
			vecty.Markup(
				vecty.Class(
					"col", "l4", "m8",
					"animate-right",
					"container",
					"padding-32",
					"center",
				),
			),
			elem.Image(
				vecty.Markup(
					vecty.Class(
						"xlarge",
						"circle",
					),
					vecty.Style(
						"width",
						"120px",
					),
					vecty.Style(
						"height",
						"120px",
					),
					prop.Src("/app/avatar.jpg"),
				),
			),
			elem.Heading2(
				vecty.Markup(
					vecty.Class(
						"serif",
					),
				),
				vecty.Text("Hasibul Hasan (Anik)"),
			),
			elem.Heading5(
				vecty.Markup(
					vecty.Class(
						"opacity",
					),
				),
				vecty.Text("Still I didn't do anything to put on bio."),
			),

			elem.Anchor(
				vecty.Markup(
					prop.Href(
						"https://github.com/AnikHasibul",
					),
					vecty.Attribute(
						"target",
						"_blank",
					),
					vecty.Class(
						"btn",
						"black",
						"xlarge",
						"animate-right",
					),
					vecty.Style(
						"width",
						"48px",
					),
					vecty.Style(
						"height",
						"48px",
					),
				),
				vecty.Text("G"),
			),
			elem.Anchor(
				vecty.Markup(
					prop.Href(
						"https://fb.me/AnikHasibul.sh",
					),
					vecty.Attribute(
						"target",
						"_blank",
					),
					vecty.Class(
						"btn",
						"indigo",
						"xlarge",
						"animate-right",
					),
					vecty.Style(
						"width",
						"48px",
					),
					vecty.Style(
						"height",
						"48px",
					),
					vecty.Style(
						"margin-left",
						"3px",
					),
				),
				vecty.Text("F"),
			),
			elem.Anchor(
				vecty.Markup(
					prop.Href(
						"https://twitter.com/iAmAnikHasibul",
					),
					vecty.Attribute(
						"target",
						"_blank",
					),
					vecty.Class(
						"btn",
						"xlarge",
						"animate-right",
					),
					vecty.Style(
						"width",
						"48px",
					),
					vecty.Style(
						"background",
						"#4289f4",
					),
					vecty.Style(
						"color",
						"#fff",
					),
					vecty.Style(
						"height",
						"48px",
					),
					vecty.Style(
						"margin-left",
						"3px",
					),
				),
				vecty.Text("T"),
			),
			elem.Anchor(
				vecty.Markup(
					prop.Href(
						"https://medium.com/@AnikHasibul",
					),
					vecty.Attribute(
						"target",
						"_blank",
					),
					vecty.Class(
						"btn",
						"xlarge",
						"black",
						"animate-right",
					),
					vecty.Style(
						"width",
						"48px",
					),
					vecty.Style(
						"height",
						"48px",
					),
					vecty.Style(
						"margin-left",
						"3px",
					),
				),
				vecty.Text("M"),
			),
		),
	)
}
